### ISSUE TITLE
可以连接上aircode，ChatGPT那边有问题。

### ISSUE THREAD

**Issue by VarPower1989** [seandong/ChatGPT-Wechat#1]
是不是因为接口问题?

**Comment by seandong** [comment]
有具体报错信息吗

**Comment by VarPower1989** [comment]
aircode那边有说OPENAI api没提供。但是key是我刚刚申请的。。。
微信里面回复一直是 问题太难。

**Comment by seandong** [comment]
看下环境变量有正确配置吗

**Comment by VarPower1989** [comment]
您说的是OPENAI_KEY和TOKEN都是安装教程写上了，是不是只有这两个？

**Comment by seandong** [comment]
> 您说的是OPENAI_KEY和TOKEN都是安装教程写上了，是不是只有这两个？

是的，阔以尝试在代码里把这两个值打印出来看下

**Comment by VarPower1989** [comment]
谢谢，我试了，可以正确打印出来。

**Comment by VarPower1989** [comment]
![IMG_20230309_095823.jpg](https://user-images.githubusercontent.com/112328682/223895978-2504fd97-a906-4aa6-ba45-c990ff701cc1.jpg)

**Comment by VarPower1989** [comment]
是不是API接口不对HongKong开放了？

**Comment by seandong** [comment]
<img width="539" alt="image" src="https://user-images.githubusercontent.com/758427/223907842-e96519c6-2535-477f-9df5-297895f4b236.png">
试下在这里把 KEY 打印出来看下呢？

**Comment by VarPower1989** [comment]
![IMG_20230309_123346.jpg](https://user-images.githubusercontent.com/112328682/223917870-efaf6a63-b5ab-457f-ba9c-8bd56ebf6c9c.jpg)

这个就是我的key，我已经打印出来了。key没有问题。这个key，我也搭了飞书，没有任何问题
