### ISSUE TITLE
aircode.io配置环境变量的时候一直提示网络错误：Network error, please try again or refresh page.

### ISSUE THREAD

**Issue by ZhuningS** [seandong/ChatGPT-Wechat#3]
aircode.io配置环境变量的时候一直提示网络错误：Network error, please try again or refresh page.
无论挂不挂VPN都会提示网络错误。
![image](https://user-images.githubusercontent.com/38108376/224221145-3ece38a0-03ef-41cc-95a8-9e69d800db15.png)

**Comment by seandong** [comment]
看起来是科学上网的问题 😁

**Comment by ZhuningS** [comment]
无论挂不挂VPN都会提示网络错误😁
