### ISSUE TITLE
token一直验证失败

### ISSUE THREAD

**Issue by ZZC-y** [seandong/ChatGPT-Wechat#8]
是token设置的不够标准还是填的地方不太对http://img.1214.work/20230326142204.png，这是填写的，大佬过目

**Comment by ZZC-y** [comment]
http://img.1214.work/20230326142204.png

**Comment by haimalianghua5523** [comment]
配置成功了吗

**Comment by zhengpeirong** [comment]
我也是这个问题，看看这篇文章，里面有成功实现的https://juejin.cn/post/7216509759415173179#comment
不知道怎样移植到这里。

**Comment by Tanktk18** [comment]
点击页面左下角的包管理器，搜索并安装 axios、sha1 和 xml2js 依赖包。_________________再增加一个 chatgpt 依赖包，测试后成功
