### ISSUE TITLE
请教大佬环境变量配置问题

### ISSUE THREAD

**Issue by haimalianghua5523** [seandong/ChatGPT-Wechat#9]

**Comment by haimalianghua5523** [comment]
![1680229624166](https://user-images.githubusercontent.com/64260133/229007286-f9b99990-2ce4-465e-83c6-df29bce12a4a.jpg)

**Comment by haimalianghua5523** [comment]
按教程来的，这一步怎么只有一个KEY

**Comment by zhengpeirong** [comment]
输入这个KEY之后按enter就有了。
